handler: lambdas/weatherApi.handler
package:
  exclude:
    - "lambdas/deployProject.js"
    - "utils/apiGateway.js"
    - "utils/cfnResponse.js"
    - "utils/npmRunBuild.js"
    - "spa"
    - "spa/**"
    - "build.sh"
environment: ${file(./apiEnv.json)}