service: weather
frameworkVersion: '2'

custom: 
  weatherApiArn: arn:aws:lambda:us-east-1:#{AWS::AccountId}:function:${self:service}-${opt:stage, self:provider.stage}-weatherApi

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  deployProject:
    handler: lambdas/deployProject.handler
    environment:
      API_ARN: ${self:custom.weatherApiArn}
  weatherApi:
    handler: lambdas/weatherApi.handler

resources:
  Resources:
    #This CF Custom Resource Deploys the entire project
    DeployProjectResource:
      Type: Custom::DeployProjectResource
      Properties:
        ServiceToken:
          Fn::GetAtt:
            - DeployProjectLambdaFunction # the logical ID in CF stack, which is the capitalized function name in serverless.yml + 'LambdaFunction'
            - Arn
